global:

  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'STAGING_resources'
    static_configs:
      - targets: ['52.28.168.133:9100']

  - job_name: 'STAGING_docker'
    static_configs:
      - targets: ['52.28.168.133:8080']

  - job_name: 'rabbitMQ_cluster_resources'
    static_configs:
      - targets: ['18.192.81.247:9100']

  - job_name: 'rabbitMQ_cluster_docker'
    static_configs:
      - targets: ['18.192.81.247:8080']


  - job_name: 'rabbitMQ_cluster_exporter'
    static_configs:
      - targets: ['18.192.81.247:9419']

  - job_name: 'MONGO_cluster_resources'
    static_configs:
      - targets: ['18.200.35.164:9100']

  - job_name: 'MONGO_cluster_docker'
    static_configs:
      - targets: ['18.200.35.164:8080']
